// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBi6HuP3xNFt1K21g98wh7rBiKhaAAcAWM',
    appId: '1:527104929271:web:22ef1fd9a3862b797e92f2',
    messagingSenderId: '527104929271',
    projectId: 'maps-7b8b8',
    authDomain: 'maps-7b8b8.firebaseapp.com',
    storageBucket: 'maps-7b8b8.appspot.com',
    measurementId: 'G-D9HLEFBNPK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5NUNAjNWACcLR5G0UWbZi79gCp4DiOlY',
    appId: '1:527104929271:android:99ecfd6c964cd9617e92f2',
    messagingSenderId: '527104929271',
    projectId: 'maps-7b8b8',
    storageBucket: 'maps-7b8b8.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBclfpMWN51hoFnUfA0E9Qgw7mkB97L5dA',
    appId: '1:527104929271:ios:bb80499f517334397e92f2',
    messagingSenderId: '527104929271',
    projectId: 'maps-7b8b8',
    storageBucket: 'maps-7b8b8.appspot.com',
    iosBundleId: 'com.example.googleMaps',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBclfpMWN51hoFnUfA0E9Qgw7mkB97L5dA',
    appId: '1:527104929271:ios:d35b8c8cf8a820e67e92f2',
    messagingSenderId: '527104929271',
    projectId: 'maps-7b8b8',
    storageBucket: 'maps-7b8b8.appspot.com',
    iosBundleId: 'com.example.googleMaps.RunnerTests',
  );
}
